name: FlutterAi

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
    
      - run: flutter pub get
      
          
      - name: Build
        run: flutter build web --release --web-renderer canvaskit
  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
